### ISSUE TITLE
Outreach Worker App

### ISSUE THREAD

**Issue by steveconners** [PCNI/OpenHMIS#14]
Add Outreach Worker App to the repository. Do not add a mess - start with the component structure, then code, then build files, then test fresh clone and compile.

**Comment by slifty** [comment]
It sounds like we may want to treat this app as a separate repository / project (which we would link to from the README.md).  Is that accurate?

**Comment by WilliamMatson** [comment]
Yes

William Matson, Executive Director
Pathways Community Network Institute
PO Box 450147
Atlanta, GA 31145-0147
[Office] 404.639.9933 x301   [Toll Free] 866.818.1032 x301
http://www.linkedin.com/in/matson
www.pcni.org

This email message, including contact information and any attachments, is
for the sole use of the intended recipient(s) and may contain confidential
and privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited. If you are not the intended recipient, please
contact the sender by reply email and destroy all copies of the original
message.

**Comment by slifty** [comment]
Got it!  I'll close out these particular "add project X to repo" issues and move the "big picture" ecosystem plans over to the wiki.  That way when folks are ready to start working on one of the apps they can spin up a repository (if it doesn't already exist)
