### ISSUE TITLE
Logging Configurations

### ISSUE THREAD

**Issue by slifty** [PCNI/OpenHMIS#20]
Right now I'm not sure where the log4j logs are being written to, and neither was my friend who set up a copy of the code.  We should resolve this in documentation and generally do an audit of the logging processes.

**Comment by ashaar364** [comment]
log4j.xml file is added. Now the log is saving in the file and also displaying on the console and log file can be found at {user.home}/logs folder.

**Comment by cecilia-donnelly** [comment]
@slifty @ashaar364:

I think this change is also in commit e25c7cb on the OAuth2.0.1 branch.  See https://github.com/PCNI/OpenHMIS/issues/19#issuecomment-118889419 for thoughts and questions.  I'm guessing that these changes should go into the 0.2.1 branch or a feature branch created from that one.

**Comment by ashaar364** [comment]
code is committed in the feature-logs branch

**Comment by kfogel** [comment]
Closing in favor of new issue #65.
