### ISSUE TITLE
Database Catalog Reference

### ISSUE THREAD

**Issue by steveconners** [PCNI/OpenHMIS#29]
(On behalf of Ashaar)
There was reference to the database catalog in a domain file that was creating a problem on the local db. I have remove that reference as in all the other domain files.

**Comment by steveconners** [comment]
Ashaar, what file are you struggling with? Rather than merge the incomplete feature branch, we will update a single file.

**Comment by ashaar364** [comment]
-@Table(name = "PATH_CLIENT_VETERAN_INFO", catalog = "openhmis")
+@Table(name = "PATH_CLIENT_VETERAN_INFO")

I have just updated the above line with the bottom line, as you can see it got the information about the schema. There shouldn't be any information about the catalog.

**Comment by ashaar364** [comment]
@steveconners One more question about the database, we don't have any foreign key relationship in the database, do we have a plan to add them? Why the relationship doesn't exist for the first place.

**Comment by steveconners** [comment]
@ashaar364  the current schema is a subset of the COMPASS ROSE schema. It is intended to provide an implementation of the API against the COMPASS ROSE schema.

A quick search of the currently checked in code shows only one instance of the catalog on line 83 of OpenHMIS/src/main/java/org/openhmis/domain/Race.java.  Where are your finding the PATH_CLIENT_VETERAN_INFO?

**Comment by ashaar364** [comment]
@steveconners, that is right current schema is a subset of the COMPASS ROSE, but we should have  relationship in the system. Having foreign key constrain in the system makes the API code different and   we have less code to write. What type of advantage we are getting by removing the relationship?

**Comment by ashaar364** [comment]
I have found the PATH_CLIENT_VETERAN_INFO in the feature-compass branch and my pull request was on that branch only and I think u r looking in the main branch.

**Comment by steveconners** [comment]
@ashaar364, the only benefit is that we have not had the time to add this. There is a further consideration that our goal is to move from this schema to the OpenHMIS2 schema developed for this purpose. HOWEVER, I expect that change will take long enough that we would reap some benefit from adding the relationships here.

**Comment by steveconners** [comment]
This does not appear to still be here (PATH_CLIENT_VETERAN_INFO) - I will close this issue. I will create another to add foreign key constraints.
