### ISSUE TITLE
Sample data has impossible value in Ethnicity field (on feature-compass_schema branch).

### ISSUE THREAD

**Issue by kfogel** [PCNI/OpenHMIS#31]
In `src/main/resources/db/data/DATA.sql` on the `feature-compass_schema` branch, the second row is data for a person named Tommy Mover.  The number in the value corresponding to column ETHNICITY_KEY is 105, which is an impossible value according to both the [HMIS CSV specification](http://www.hudhdx.info/Resources/Vendors/4_0/HMISCSVSpecifications4_0FINAL.pdf) and the [HMIS Data Dictionary](https://www.hudexchange.info/resources/documents/HMIS-Data-Dictionary.pdf) (actually I'm using the later August 2014 revision of the data dictionary, which I don't have an online link for, but it doesn't differ from the document at the preceding link regarding Ethnicity anyway).

The allowed values for Ethnicity are:

```
 0  ==  Non-Hispanic/Non-Latino
 1  ==  Hispanic/Latino
 8  ==  Client doesn't know
 9  ==  Client refused
99  ==  Data not collected
```

When I visit that client record at `http://localhost:8080/openhmis/services/clients/336823`, I see `"ethnicity":105` too.

Actually, now that I look at other rows in DATA.sql, a lot of people seem to have impossible values for Ethnicity -- 104, 105, etc.

(This is all as of commit e76fa31 by the way, but I pulled and got commit 55b2981 and it seems to be true there too.)

**Comment by steveconners** [comment]
The COMPASS ROSE dataset has data created prior to the 2014 Data Standards and data created for non-HMIS communities.

The test data uses the PATH_CODE_ETHNICITY table as the lookup. The historical data uses existing system keys.
The discrepancy was discussed verbally -- that the COMPASS ROSE-specific DAO would need to handle legacy keys that do not match the standard.

This is an instance of key mismatch (COMPASS ROSE maps 104 to 0, and 105 to 1)

While you may not encounter it in the test data, the historical record also includes keys which are no longer valid responses or which have been divided and separated into multiple responses. The lookup tables used by COMPASS ROSE can be found here: 
 https://github.com/PCNI/OpenHMIS/blob/feature-compass_schema/docs/API_to_Schema_Mapping.md
and the noted lookup tables are in the test data set here:
 https://drive.google.com/open?id=0B6jU7mYT7ztJVTNCZ1NEaXBMcXM

**Comment by slifty** [comment]
That is indeed a bug!  Before I learned about that CSV standards file I had made the first ENUMs based on sample data (ethnicity being the first one -- must have missed it when I went back to re-code based on HUD).  The Manager object that does the mapping will ultimately be responsible for implementing the logic Steve just mentioned.

I'll make this fix this afternoon.

**Comment by slifty** [comment]
Karl this should now be fixed -- can you let me know if export is still showing invalid fields?

**Comment by kfogel** [comment]
But, @steveconners's (implicit) point is still correct I think: I misfiled this as a bug against the sample data when it was actually a bug in the values returned by the API.  The `DATA.sql` file can have whatever it wants -- it can have a rutabaga in that field if it chooses to.  As long as the DAO maps it correctly to a HUD-approved value, we're good.

Will test and let you know, @slifty.

**Comment by slifty** [comment]
Yep -- sorry, I should have clarified that the fix had nothing to do with the DATA.sql file!  Also I should have mentioned this issue in the commit... Fail :(

**Comment by kfogel** [comment]
@cecilia-donnelly confirms this is fixed now.  Closing.
