### ISSUE TITLE
Convert Using the OpenHMIS VM Guide to Markdown

### ISSUE THREAD

**Issue by steveconners** [PCNI/OpenHMIS#7]

**Comment by slifty** [comment]
Since we have switched over to being able to avoid the need for a VM to have a local build, do we want to keep that as part of the repo / documentation or should we close this issue off?

**Comment by steveconners** [comment]
I will move this into the wiki.

**Comment by steveconners** [comment]
[OpenHMIS-Development-VM](../wiki/OpenHMIS-Development-VM)
