### ISSUE TITLE
Minor inconsistency in a couple of log.info() calls; needs examination.

### ISSUE THREAD

**Issue by kfogel** [PCNI/OpenHMIS#78]
Commit f522fa4 adds a couple of comments asking questions about a choice of parameter in log.info() calls.  See the commit for details.

**Comment by cecilia-donnelly** [comment]
@kfogel, I think these just snuck through before I realized that it would make more sense to use the ID that we already had in the method.  I'll fix them.

**Comment by kfogel** [comment]
Thanks!
