### ISSUE TITLE
Document HTTP response codes in docs/API.md.

### ISSUE THREAD

**Issue by kfogel** [PCNI/OpenHMIS#79]
In general, [API.md](https://github.com/hmis-tools/hmis-api-server/blob/master/docs/API.md) doesn't talk much about HTTP response codes, although it talks about response bodies.  We should specify the response codes too, right?

In commit 74ceae5, I included some text that mentions HTTP response code (for DELETE of a Consent-to-Share Record), but as far as I can tell, that's the first place we talk about it.

**Comment by slifty** [comment]
I'm OK with that idea, however the main reason we might not is because our API because response _codes_ are standardized across the web, and our documentation wouldn't be particularly different from those standards: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by kfogel** [comment]
Documented in commit 69ffc87 (should have mentioned this issue in the commit message, but forgot to).
