### ISSUE TITLE
User schema fields break standard

### ISSUE THREAD

**Issue by slifty** [PCNI/OpenHMIS#81]
Our schema usually appends"Id" to foreign key fields, so `organization` should be `organizationId` and `coc` should be `cocId`. 

Also we tend to reference `coc` as `coC` -- whether or not coc would be better, coC is used in most places and mixing it up is a little wonky.

This is currently defined in hmis-api-server/src/main/resources/db/migration/V029__ALTER_TMP_USER.sql -- we should create another migration file to change it.

**Comment by cecilia-donnelly** [comment]
@slifty thanks for pointing this out.  I will fix it.  Do you think it's worth creating the organization and CoC tables at the same time, so the foreign keys have somewhere to point to?

**Comment by slifty** [comment]
We have both of those already I believe

**Comment by cecilia-donnelly** [comment]
Oh right, I see `TMP_ORGANIZATION` and `TMP_PROJECT_CONTINUUM` now.  Thanks!
